### ISSUE TITLE
Using kdeconnect-cli

### ISSUE THREAD

**Issue by robert7k** [phpmoli/kdeconnect-chrome#4]
You have this question in your readme:

> Why install a package and not using kdeconnect-cli? Here's why:
> 
>     $ kdeconnect-cli --device android --ping
> 
>     QDBusConnection: error: could not send message to service "org.kde.kdeconnect" path "/modules/kdeconnect/devices/android/ping" interface "org.kde.kdeconnect.device.ping" member "sendPing": Invalid object path: /modules/kdeconnect/devices/android/ping
> 
> Google and irc couldnt help, glad if you can.

The problem is that you reference your phone by its name instead of its id. You should use the parameter -n (or --name) instead of --device to access it by name:

     $ kdeconnect-cli --name android --ping

I posted this as an issue because I couldn't find an email address of you. I hope this helps.

**Comment by phpmoli** [comment]
Hello @robert7k ,
Thank you for your help!
My problems with this are:

1. why isnt this option listed in the `--help` ?

2. `$ kdeconnect-cli --list-devices
- myandroid: bc61836a282b2b7e (paired and reachable)
1 devices found
$ kdeconnect-cli --name myandroid --ping
kdeconnect-cli: No device specified`

Granted, the `--device id` works, but the command does not give any result whether it was successful or not:
`$ kdeconnect-cli --device bc61836a282b2b7e --ping
$ echo $?
0
$ kdeconnect-cli --device bc61836a282b2b7f --ping
$ echo $?
0`
We dont know if the device was connected, and we can see this info currently when the gui comes up, so i will keep it this way :/

**Comment by thesbros** [comment]
By the way, the `--name` option is now in the help command, and it now changes the exit code depending on success.

**Comment by phpmoli** [comment]
Dear @thesbros ,
Thanks for the info!
I use debian-stable and kdeconnect-cli hasnt got those new features, so it would still require a not-default dependency, like package-pinning or so, so i would wait with this.
That being said, this code is so extemely simple, someone should fork it with this change and easily publish that in the chrome store.
